[workspace]
members = [
    "zargo",

    "zinc-compiler",
    "zinc-tester",
    "zinc-vm",
    "zandbox",
    "schnorr",

    "zinc-source",
    "zinc-build",
    "zinc-utils",
    "zinc-const",
]
