[package]
name = "compiler"
version = "0.1.0"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
failure = "0.1"
proc-macro2 = "0.4"

# rand = "0.4.5"
# hex = "0.3.2"
# time = "0.1"
# num-bigint = "0.2"
#
# ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }
# pairing = { package = "pairing_ce", version = "0.17.0" }
# bellman = { package = "bellman_ce", version = "0.3.0" }
# franklin_crypto = { package = "franklin-crypto", git = "ssh://git@github.com/matter-labs/franklin-crypto.git" }
# franklin_crypto = { package = "franklin-crypto", git = "ssh://git@gitlab.mattr.network/matter-labs/franklin-crypto.git" }
# franklin-crypto = { package = "sapling-crypto_ce", version = "0.0.5" }
# franklin-crypto = { path = "franklin-crypto" }
