[workspace]
members = [
    "zinc-lexical",
    "zinc-syntax",
    "zinc-compiler",

    "zinc-tester",
    "zinc-vm",
    "zargo",
    "zandbox",

    "zinc-data",
    "zinc-build",
    "zinc-utils",
    "zinc-const",
]

exclude = [
    "zksync"
]
