[workspace]
members = [
    "zargo",

    "zinc-compiler",
    "zinc-bytecode",
    "zinc-utils",
    "zinc-const",
    "zinc-vm",
    "zinc-server",
    "zinc-mongo",
    "zinc-tester",

    "schnorr",
]
