[package]
name = "zrust-bytecode"
version = "0.5.0"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
edition = "2018"
description = "The ZRust bytecode"

[[bin]]
name = "zrustv"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.7"
structopt = "0.3"
failure = "0.1"
