[package]
name = "zinc-vm"
version = "0.1.5"
authors = [
    "Alexander Movchan <am@matterlabs.dev>",
    "hedgar2017 <hedgar2017@gmail.com>",
]
edition = "2018"
description = "The Zinc virtual machine"

[[bin]]
name = "zvm"
path = "src/cli/zvm.rs"

[dependencies]
log = "0.4"
env_logger = "0.7"
structopt = "0.3"
failure = "0.1"
colored = "1.9"

serde_json = "1.0"

lazy_static = "1.4"
rand = "0.4"
hex = "0.4"

num-bigint = "0.2"
num-traits = "0.2"

sha2 = "0.8"

pairing = { package = "pairing_ce", version = "0.17.0" }
bellman = { package = "bellman_ce", version = "0.3.0" }
franklin_crypto = { package = "franklin-crypto", git = "https://github.com/matter-labs/franklin-crypto.git", branch = "zinc" }
ff = { package = "ff_ce", version = "0.6.0", features = ["derive"] }

zinc-bytecode = { path = "../zinc-bytecode" }
zinc-utils = { path = "../zinc-utils" }
