[package]
name = "zinc-const"
version = "0.1.5"
authors = [
    "hedgar2017 <hedgar2017@gmail.com>",
    "Alexander Movchan <am@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc constants"

[dependencies]
