[package]
name = "zinc-const"
version = "0.1.5"
authors = [
    "Alex Z <a.zarudnyy@matterlabs.dev>",
    "Alexander Movchan <am@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc constants"

[dependencies]
