[package]
name = "zargo"
version = "0.1.5"
authors = ["Alex Z <a.zarudnyy@matterlabs.dev>"]
edition = "2018"
description = "The Zinc project manager"

[[bin]]
name = "zargo"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.7"
structopt = "0.3"

failure = "0.1"
colored = "1.9"
toml = "0.5"

serde = "1.0"
serde_derive = "1.0"
Inflector = "0.11"

zinc-const = { path = "../zinc-const" }
zinc-utils = { path = "../zinc-utils" }
