[package]
name = "zargo"
version = "0.2.0"
authors = [
    "Alex Zarudnyy <a.zarudnyy@matterlabs.dev>",
]
edition = "2018"
description = "The Zinc project manager"

[[bin]]
name = "zargo"
path = "src/main.rs"

[dependencies]
log = "0.4"
structopt = "0.3"

failure = "0.1"
colored = "2.0"
toml = "0.5"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
Inflector = "0.11"

reqwest = "0.9.24"

zinc-const = { path = "../zinc-const" }
zinc-utils = { path = "../zinc-utils" }
zinc-source = { path = "../zinc-source" }
