[package]
name = "zinc-compiler"
version = "0.5.0"
authors = ["hedgar2017 <hedgar2017@gmail.com>"]
edition = "2018"
description = "The Zinc compiler"

[[bin]]
name = "znc"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.7"
structopt = "0.3"
failure = "0.1"
num-traits = "0.2"
num-bigint = "0.2"

zinc-bytecode = { path = "../zinc-bytecode" }
