[package]
name = "zinc-tester"
version = "0.2.0"
authors = ["Alex Z <a.zarudnyy@matterlabs.dev>"]
edition = "2018"
description = "The Zinc integration test runner"

[[bin]]
name = "zinc-tester"
path = "src/zinc-tester/main.rs"

[dependencies]
structopt = "0.3"
failure = "0.1"
colored = "1.9"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rayon = "1.3"

zinc-const = { path = "../zinc-const" }
zinc-compiler = { path = "../zinc-compiler" }
zinc-build = { path = "../zinc-build" }
zinc-vm = { path = "../zinc-vm" }
